spring:
  profiles:
    active: dev
  application:
    name: AppStore

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.mdv.appstore.dto

file:
  image: 
    allowed-extensions: jpg, jpeg, png, gif
    path-prefix: /image/

app:
  api:
    version: v1
    base-url: /api/${app.api.version}

logging:
  file:
    max-size: 10MB
    max-history: 10
    total-size-cap: 100MB
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"